### ISSUE TITLE
Bot doesn't start playing the music from the beggining

### ISSUE THREAD

**Issue by 1Gigabit** [KGT1/jellyfin-discord-music-bot#12]
Unsure if this is a jellyfin issue or a bot issue. 

When I play my music it takes atleast 22 seconds for it to start actually playing, and it starts 22 seconds into the song. 

I believe this is the full log of the container from when I started it last and made it play.

Only few songs have this issue & it didn't do this before and used to play the full song.
```
> jellyfin-discord-music-bot@0.0.1 start /app
> node src/index.js

Error opening cache: ReferenceError: self is not defined
ApiClient serverAddress: https://REDACTED:8443/
ApiClient appName: Jellyfin Discord Music Bot
ApiClient appVersion: 0.0.1
ApiClient deviceName: cb6264268210
ApiClient deviceId: cb6264268210
Requesting url without automatic networking: https://REDACTED:8443//Users/authenticatebyname

> jellyfin-discord-music-bot@0.0.1 start /app
> node src/index.js

Error opening cache: ReferenceError: self is not defined
ApiClient serverAddress: https://REDACTED:8443/
ApiClient appName: Jellyfin Discord Music Bot
ApiClient appVersion: 0.0.1
ApiClient deviceName: cb6264268210
ApiClient deviceId: cb6264268210
Requesting url without automatic networking: https://REDACTED:8443//Users/authenticatebyname
Requesting https://REDACTED:8443//Search/Hints?searchTerm=Pig&includeItemTypes=Audio%2CMusicAlbum%2CPlaylist
Requesting https://REDACTED:8443//Users/6bf25102d3684a44b6f2c6f7bbd35cf0/Items/ced794045065bade99a8d7c3a87f9dca
Requesting url without automatic networking: https://REDACTED:8443//Sessions/Playing
Requesting https://REDACTED:8443//Users/6bf25102d3684a44b6f2c6f7bbd35cf0/Items/ced794045065bade99a8d7c3a87f9dca
(node:28) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'embeds' of undefined
    at InterActivePlayMessage.updateCurrentSongMessage (/app/src/InterActivePlayMessage.js:141:27)
    at Object.updateCurrentSongMessage (/app/src/interactivemsghandler.js:50:8)
    at updatePlayMessage (/app/src/playbackmanager.js:101:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:28) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Requesting https://REDACTED:8443//System/Endpoint
Requesting url without automatic networking: https://REDACTED:8443//Sessions/Playing
Requesting url without automatic networking: https://REDACTED:8443//Sessions/Playing
Requesting url without automatic networking: https://REDACTED:8443//Sessions/Playing/Stopped
```

**Comment by KGT1** [comment]
Hey what Jellyfin Server version are you using?

**Comment by 1Gigabit** [comment]
@KGT1 Sorry for late reply.
I am using Jellyfin version 10.6.4

I'd like to point out that this kind of fixed it self over time as I was using the bot. I believe the issue only occurs when I use the Jellyfin web interface to remote control the bot.

**Comment by KGT1** [comment]
dont know whats wrong and seems to have fixed itself so closing this?
