### ISSUE TITLE
TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by CarbonMac** [KGT1/jellyfin-discord-music-bot#21]
```
(node:37) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/app/node_modules/node-fetch/lib/index.js:1305:9)
    at /app/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/app/node_modules/node-fetch/lib/index.js:1407:9)
    at I (/app/node_modules/jellyfin-apiclient/dist/jellyfin-apiclient.js:5:3420)
    at e.value (/app/node_modules/jellyfin-apiclient/dist/jellyfin-apiclient.js:5:10625)
    at e.value (/app/node_modules/jellyfin-apiclient/dist/jellyfin-apiclient.js:5:11556)
    at /app/node_modules/jellyfin-apiclient/dist/jellyfin-apiclient.js:5:12749
    at new Promise (<anonymous>)
    at e.value (/app/node_modules/jellyfin-apiclient/dist/jellyfin-apiclient.js:5:12692)
```

**Comment by KGT1** [comment]
Hey sorry, i meant the url you set the bot to either in the config file or in the JELLYFIN_SERVER_ADDRESS env var.

**Comment by CarbonMac** [comment]
Same thing when trying each respectively (without the / at the end)
